from __future__ import annotations

ENTITY_SEEDS = [
    {
        "canonical_term": "niacinamide",
        "aliases": ["niacinamide", "vitamin b3", "nicotinamide"],
        "entity_type": "ingredient",
        "hb_category": "skincare",
        "origin_market": "US",
        "description": "Brightening ingredient commonly used in serums and toners.",
    },
    {
        "canonical_term": "tranexamic acid",
        "aliases": ["tranexamic acid", "txa", "tranexamic"],
        "entity_type": "ingredient",
        "hb_category": "skincare",
        "origin_market": "JP",
        "description": "Ingredient often used for pigmentation and tone-evening products.",
    },
    {
        "canonical_term": "ceramide",
        "aliases": ["ceramide", "ceramides", "barrier lipids"],
        "entity_type": "ingredient",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "Barrier-support ingredient associated with hydration and repair.",
    },
    {
        "canonical_term": "retinol",
        "aliases": ["retinol", "vitamin a", "retinoid"],
        "entity_type": "ingredient",
        "hb_category": "skincare",
        "origin_market": "US",
        "description": "Well-known anti-aging active with resurfacing benefits.",
    },
    {
        "canonical_term": "snail mucin",
        "aliases": ["snail mucin", "snail secretion", "snail essence"],
        "entity_type": "ingredient",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "Hydration and soothing ingredient popular in Korean skincare.",
    },
    {
        "canonical_term": "cica",
        "aliases": ["cica", "centella", "centella asiatica"],
        "entity_type": "ingredient",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "Calming ingredient used in sensitive-skin and redness formulas.",
    },
    {
        "canonical_term": "bakuchiol",
        "aliases": ["bakuchiol"],
        "entity_type": "ingredient",
        "hb_category": "skincare",
        "origin_market": "EU",
        "description": "Plant-derived ingredient positioned as a gentler retinol alternative.",
    },
    {
        "canonical_term": "glass skin",
        "aliases": ["glass skin", "dewy skin"],
        "entity_type": "function",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "A glow-focused skincare outcome associated with layered hydration.",
    },
    {
        "canonical_term": "skin barrier repair",
        "aliases": ["skin barrier repair", "barrier repair", "skin barrier"],
        "entity_type": "function",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "A repair and recovery positioning that often tracks ceramide-led products.",
    },
    {
        "canonical_term": "double cleanse",
        "aliases": ["double cleanse", "double cleansing"],
        "entity_type": "function",
        "hb_category": "skincare",
        "origin_market": "JP",
        "description": "A two-step cleansing routine combining oil and water-based cleansers.",
    },
    {
        "canonical_term": "COSRX",
        "aliases": ["cosrx"],
        "entity_type": "brand",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "K-beauty brand known for active-led skincare products.",
    },
    {
        "canonical_term": "Beauty of Joseon",
        "aliases": ["beauty of joseon", "boj"],
        "entity_type": "brand",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "K-beauty brand with heritage-inspired formulations and strong social buzz.",
    },
    {
        "canonical_term": "Torriden",
        "aliases": ["torriden"],
        "entity_type": "brand",
        "hb_category": "skincare",
        "origin_market": "KR",
        "description": "Hydration-focused Korean skincare brand often linked with serum trends.",
    },
    {
        "canonical_term": "SPF serum",
        "aliases": ["spf serum", "serum sunscreen"],
        "entity_type": "product_type",
        "hb_category": "skincare",
        "origin_market": "US",
        "description": "Hybrid skincare and sun-care format positioned for daily wear.",
    },
    {
        "canonical_term": "hair growth tonic",
        "aliases": ["hair growth tonic", "scalp tonic"],
        "entity_type": "product_type",
        "hb_category": "haircare",
        "origin_market": "JP",
        "description": "Haircare format positioned for scalp health and growth support.",
    },
]


SALES_SKU_SEEDS = [
    {
        "sku": "HK-TXA-001",
        "product_name": "Radiance TXA Serum",
        "brand": "Beauty of Joseon",
        "ingredient_tags": ["tranexamic acid", "niacinamide"],
        "category": "skincare",
    },
    {
        "sku": "HK-CER-001",
        "product_name": "Barrier Rescue Cream",
        "brand": "COSRX",
        "ingredient_tags": ["ceramide", "cica"],
        "category": "skincare",
    },
    {
        "sku": "HK-SNA-001",
        "product_name": "Snail Recovery Essence",
        "brand": "COSRX",
        "ingredient_tags": ["snail mucin"],
        "category": "skincare",
    },
    {
        "sku": "KR-BAK-001",
        "product_name": "Gentle Renewal Serum",
        "brand": "Torriden",
        "ingredient_tags": ["bakuchiol", "cica"],
        "category": "skincare",
    },
    {
        "sku": "TW-SPF-001",
        "product_name": "Everyday Shield SPF Serum",
        "brand": "Beauty of Joseon",
        "ingredient_tags": ["niacinamide"],
        "category": "skincare",
    },
    {
        "sku": "SG-HAIR-001",
        "product_name": "Root Balance Hair Growth Tonic",
        "brand": "Some By Mi",
        "ingredient_tags": ["cica"],
        "category": "haircare",
    },
]
